#!/usr/bin/env python
from boids.run_boids import parse_args, load_config, run_boids

cfgdata = parse_args()
if cfgdata["from_file"]:
    cfgdata = load_config(cfgdata["from_file"])
run_boids(cfgdata)
